# Generated by Django 4.0.4 on 2022-04-30 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Legal name')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('pincode', models.CharField(max_length=50, verbose_name='Pincode')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone no.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.CharField(max_length=250, verbose_name='Website')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companys',
            },
        ),
    ]
