# Generated by Django 4.0.4 on 2022-04-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_primarygroup_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Ledger')),
                ('under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Under')),
            ],
            options={
                'verbose_name': 'ledger',
                'verbose_name_plural': 'ledgers',
            },
        ),
    ]
