# Generated by Django 4.0.4 on 2022-04-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primarygroup',
            options={'verbose_name': 'Primary Group', 'verbose_name_plural': 'Primary Groups'},
        ),
        migrations.AddField(
            model_name='ledger',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='opening',
            field=models.IntegerField(blank=True, null=True, verbose_name='Opening Balance'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name of Ledger'),
        ),
    ]
