# Generated by Django 4.0.4 on 2022-05-01 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('sn', models.CharField(max_length=50, verbose_name='Voucher No.')),
                ('rn', models.CharField(max_length=50, verbose_name='Reference No.')),
                ('nar', models.TextField(verbose_name='Narration')),
                ('dr', models.IntegerField(verbose_name='Debit Amount')),
                ('cr', models.IntegerField(verbose_name='Credit Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to='core.ledger', verbose_name='Account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ledger', verbose_name='Ledger Accounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voucher', verbose_name='Voucher Type')),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journals',
            },
        ),
    ]
