# Generated by Django 4.0.4 on 2022-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'journal', 'verbose_name_plural': 'journal'},
        ),
        migrations.AlterField(
            model_name='journal',
            name='nar',
            field=models.TextField(blank=True, null=True, verbose_name='Narration'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='rn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voucher No.'),
        ),
    ]
