# Generated by Django 4.0.4 on 2022-05-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_journal_options_alter_journal_nar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='cr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='dr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Debit Amount'),
        ),
    ]
