# Generated by Django 4.0.4 on 2022-05-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_journal_cr_alter_journal_dr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='ledger',
        ),
        migrations.AddField(
            model_name='journal',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to='core.ledger', verbose_name='By'),
        ),
        migrations.AddField(
            model_name='journal',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ledger', verbose_name='To'),
        ),
    ]
