# Generated by Django 4.0.4 on 2022-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_journal_account_remove_journal_ledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='dr',
        ),
        migrations.AddField(
            model_name='journal',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
